import { PAGE } from "../utils/pages"

const pages: Record<number, PAGE> = {
  4: PAGE.FOREST_ASCENSION,
  5: PAGE.FOREST_CHAPTER_ONE,
  6: PAGE.FOREST_MIDNIGHT_MASS,
  7: PAGE.FOREST_MIDNIGHT_MASS,
  8: PAGE.FOREST_NOCTURNE_EMBRACE,
  9: PAGE.FOREST_CHAPTER_TWO,
  10: PAGE.FOREST_CRYSTAL_SPEARS,
  11: PAGE.FOREST_ZERO_HOUR,
  12: PAGE.FOREST_INEXPLICABLE_CALM,
  13: PAGE.FOREST_ENTITIES,
  14: PAGE.FOREST_MACHINES,
  15: PAGE.FOREST_CHAPTER_FOUR,
  16: PAGE.FOREST_PALISADES_OF_REALITY,
  17: PAGE.FOREST_TWO,
  18: PAGE.FOREST_THE_LIGHT,
}

export default pages
